# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # config.vm.box = "debian/buster64"

  # config.vm.provider "virtualbox" do |vb|
  #   vb.memory = "1024"
  # end

  # config.vm.box_check_update = false


  config.vm.define "web" do |web|
    web.vm.box = "debian/buster64"

    web.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    web.vm.synced_folder ".", "/vagrant"
    web.vm.network "forwarded_port", guest: 80, host: 8080, id: "nginx"

    web.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "web/playbook.yml"
    end
  end
  
  # config.vm.define "db" do |db|
  #   db.vm.box = "debian/buster64"

  #   db.vm.provider "virtualbox" do |vb|
  #     vb.memory = "1024"
  #   end

  #   # db.vm.provision "ansible_local" do |ansible|
  #   #   ansible.playbook = "playbook_db.yml"
  #   #   ansible.install_mode = "pip"
  #   #   ansible.version = "2.2.1.0"
  #   # end
  # end



  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
